export const TIMELINE_HOURS_IN_DAY = 24;
export const TIMELINE_EXTRA_DAY_HOURS = 24;
export const TIMELINE_TOTAL_HOURS = TIMELINE_HOURS_IN_DAY + TIMELINE_EXTRA_DAY_HOURS * 2;
export const TIMELINE_HOUR_WIDTH = 74;
export const TIMELINE_DRAG_ENABLED = false;
