export const TIMELINE_HOUR_MS = 60 * 60 * 1000;
export const TIMELINE_HOURS_IN_DAY = 24;
export const TIMELINE_EXTRA_DAY_HOURS = 24;
export const TIMELINE_TOTAL_HOURS = TIMELINE_HOURS_IN_DAY + TIMELINE_EXTRA_DAY_HOURS * 2;
export const TIMELINE_HOUR_WIDTH = 74;
export const TIMELINE_SNAP_DELAY_MS = 120;
export const TIMELINE_SNAP_RELEASE_MS = 260;
