export type FavoriteCity = {
  id: string;
  cityId?: string;
  order: number;
  customName: string;
  city: string;
  displayCity?: string;
  timezone: string;
  utcOffset: string;
  timeOffset: string;
  time: string;
  period: 'morning' | 'day' | 'evening' | 'night';
  visible?: boolean;
  isTomorrow?: boolean;
};

type FavoriteCityFixture = Omit<FavoriteCity, 'order'>;

const cityFixtures: FavoriteCityFixture[] = [
  {
    id: 'baker-island',
    customName: '',
    city: 'Baker Island',
    timezone: 'Etc/GMT+12',
    utcOffset: 'UTC-12:00',
    timeOffset: 'UTC-12',
    time: '10:45',
    period: 'day',
  },
  {
    id: 'pago-pago',
    customName: '',
    city: 'Pago Pago',
    timezone: 'Pacific/Pago_Pago',
    utcOffset: 'UTC-11:00',
    timeOffset: 'UTC-11',
    time: '11:45',
    period: 'day',
  },
  {
    id: 'honolulu',
    customName: '',
    city: 'Honolulu',
    timezone: 'Pacific/Honolulu',
    utcOffset: 'UTC-10:00',
    timeOffset: 'UTC-10',
    time: '12:45',
    period: 'day',
  },
  {
    id: 'taiohae',
    customName: '',
    city: 'Taiohae',
    timezone: 'Pacific/Marquesas',
    utcOffset: 'UTC-09:30',
    timeOffset: 'UTC-9:30',
    time: '13:15',
    period: 'day',
    visible: false,
  },
  {
    id: 'gambier-islands',
    customName: '',
    city: 'Gambier Islands',
    timezone: 'Pacific/Gambier',
    utcOffset: 'UTC-09:00',
    timeOffset: 'UTC-9',
    time: '13:45',
    period: 'day',
  },
  {
    id: 'los-angeles',
    customName: '',
    city: 'Los Angeles',
    timezone: 'America/Los_Angeles',
    utcOffset: 'UTC-08:00',
    timeOffset: 'UTC-8',
    time: '14:45',
    period: 'day',
  },
  {
    id: 'denver',
    customName: '',
    city: 'Denver',
    timezone: 'America/Denver',
    utcOffset: 'UTC-07:00',
    timeOffset: 'UTC-7',
    time: '15:45',
    period: 'day',
  },
  {
    id: 'mexico-city',
    customName: '',
    city: 'Mexico City',
    timezone: 'America/Mexico_City',
    utcOffset: 'UTC-06:00',
    timeOffset: 'UTC-6',
    time: '16:45',
    period: 'day',
  },
  {
    id: 'new-york',
    customName: '',
    city: 'New York',
    timezone: 'America/New_York',
    utcOffset: 'UTC-05:00',
    timeOffset: 'UTC-5',
    time: '17:45',
    period: 'day',
  },
  {
    id: 'santiago',
    customName: '',
    city: 'Santiago',
    timezone: 'America/Santiago',
    utcOffset: 'UTC-04:00',
    timeOffset: 'UTC-4',
    time: '18:45',
    period: 'night',
  },
  {
    id: 'st-johns',
    customName: '',
    city: "St. John's",
    timezone: 'America/St_Johns',
    utcOffset: 'UTC-03:30',
    timeOffset: 'UTC-3:30',
    time: '19:15',
    period: 'night',
  },
  {
    id: 'rio-de-janeiro',
    customName: '',
    city: 'Rio de Janeiro',
    timezone: 'America/Sao_Paulo',
    utcOffset: 'UTC-03:00',
    timeOffset: 'UTC-3',
    time: '19:45',
    period: 'night',
  },
  {
    id: 'fernando-de-noronha',
    customName: '',
    city: 'Fernando de Noronha',
    timezone: 'America/Noronha',
    utcOffset: 'UTC-02:00',
    timeOffset: 'UTC-2',
    time: '20:45',
    period: 'night',
  },
  {
    id: 'ponta-delgada',
    customName: '',
    city: 'Ponta Delgada',
    timezone: 'Atlantic/Azores',
    utcOffset: 'UTC-01:00',
    timeOffset: 'UTC-1',
    time: '21:45',
    period: 'night',
  },
  {
    id: 'london',
    customName: '',
    city: 'London',
    timezone: 'Europe/London',
    utcOffset: 'UTC+00:00',
    timeOffset: 'UTC+0',
    time: '22:45',
    period: 'night',
  },
  {
    id: 'paris',
    customName: '',
    city: 'Paris',
    timezone: 'Europe/Paris',
    utcOffset: 'UTC+01:00',
    timeOffset: 'UTC+1',
    time: '23:45',
    period: 'night',
  },
  {
    id: 'cape-town',
    customName: '',
    city: 'Cape Town',
    timezone: 'Africa/Johannesburg',
    utcOffset: 'UTC+02:00',
    timeOffset: 'UTC+2',
    time: '00:45',
    period: 'night',
    isTomorrow: true,
  },
  {
    id: 'nairobi',
    customName: '',
    city: 'Nairobi',
    timezone: 'Africa/Nairobi',
    utcOffset: 'UTC+03:00',
    timeOffset: 'UTC+3',
    time: '01:45',
    period: 'night',
    isTomorrow: true,
  },
  {
    id: 'tehran',
    customName: '',
    city: 'Tehran',
    timezone: 'Asia/Tehran',
    utcOffset: 'UTC+03:30',
    timeOffset: 'UTC+3:30',
    time: '02:15',
    period: 'night',
    isTomorrow: true,
  },
  {
    id: 'dubai',
    customName: '',
    city: 'Dubai',
    timezone: 'Asia/Dubai',
    utcOffset: 'UTC+04:00',
    timeOffset: 'UTC+4',
    time: '02:45',
    period: 'night',
    isTomorrow: true,
  },
  {
    id: 'kabul',
    customName: '',
    city: 'Kabul',
    timezone: 'Asia/Kabul',
    utcOffset: 'UTC+04:30',
    timeOffset: 'UTC+4:30',
    time: '03:15',
    period: 'night',
    isTomorrow: true,
  },
  {
    id: 'maldives',
    customName: '',
    city: 'Maldives',
    timezone: 'Indian/Maldives',
    utcOffset: 'UTC+05:00',
    timeOffset: 'UTC+5',
    time: '03:45',
    period: 'night',
    isTomorrow: true,
  },
  {
    id: 'mumbai',
    customName: '',
    city: 'Mumbai',
    timezone: 'Asia/Kolkata',
    utcOffset: 'UTC+05:30',
    timeOffset: 'UTC+5:30',
    time: '04:15',
    period: 'night',
    isTomorrow: true,
  },
  {
    id: 'kathmandu',
    customName: '',
    city: 'Kathmandu',
    timezone: 'Asia/Kathmandu',
    utcOffset: 'UTC+05:45',
    timeOffset: 'UTC+5:45',
    time: '04:30',
    period: 'night',
    isTomorrow: true,
  },
  {
    id: 'dhaka',
    customName: '',
    city: 'Dhaka',
    timezone: 'Asia/Dhaka',
    utcOffset: 'UTC+06:00',
    timeOffset: 'UTC+6',
    time: '04:45',
    period: 'night',
    isTomorrow: true,
  },
  {
    id: 'yangon',
    customName: '',
    city: 'Yangon',
    timezone: 'Asia/Yangon',
    utcOffset: 'UTC+06:30',
    timeOffset: 'UTC+6:30',
    time: '05:15',
    period: 'morning',
    isTomorrow: true,
  },
  {
    id: 'bangkok',
    customName: '',
    city: 'Bangkok',
    timezone: 'Asia/Bangkok',
    utcOffset: 'UTC+07:00',
    timeOffset: 'UTC+7',
    time: '05:45',
    period: 'morning',
    isTomorrow: true,
  },
  {
    id: 'singapore',
    customName: '',
    city: 'Singapore',
    timezone: 'Asia/Singapore',
    utcOffset: 'UTC+08:00',
    timeOffset: 'UTC+8',
    time: '06:45',
    period: 'morning',
    isTomorrow: true,
  },
  {
    id: 'eucla',
    customName: '',
    city: 'Eucla',
    timezone: 'Australia/Eucla',
    utcOffset: 'UTC+08:45',
    timeOffset: 'UTC+8:45',
    time: '07:30',
    period: 'morning',
    visible: false,
    isTomorrow: true,
  },
  {
    id: 'tokyo',
    customName: '',
    city: 'Tokyo',
    timezone: 'Asia/Tokyo',
    utcOffset: 'UTC+09:00',
    timeOffset: 'UTC+9',
    time: '07:45',
    period: 'morning',
    isTomorrow: true,
  },
  {
    id: 'darwin',
    customName: '',
    city: 'Darwin',
    timezone: 'Australia/Darwin',
    utcOffset: 'UTC+09:30',
    timeOffset: 'UTC+9:30',
    time: '08:15',
    period: 'day',
    isTomorrow: true,
  },
  {
    id: 'sydney',
    customName: '',
    city: 'Sydney',
    timezone: 'Australia/Sydney',
    utcOffset: 'UTC+10:00',
    timeOffset: 'UTC+10',
    time: '08:45',
    period: 'day',
    isTomorrow: true,
  },
  {
    id: 'lord-howe-island',
    customName: '',
    city: 'Lord Howe Island',
    timezone: 'Australia/Lord_Howe',
    utcOffset: 'UTC+10:30',
    timeOffset: 'UTC+10:30',
    time: '09:15',
    period: 'day',
    visible: false,
    isTomorrow: true,
  },
  {
    id: 'noumea',
    customName: '',
    city: 'Noumea',
    timezone: 'Pacific/Noumea',
    utcOffset: 'UTC+11:00',
    timeOffset: 'UTC+11',
    time: '09:45',
    period: 'day',
    isTomorrow: true,
  },
  {
    id: 'auckland',
    customName: '',
    city: 'Auckland',
    timezone: 'Pacific/Auckland',
    utcOffset: 'UTC+12:00',
    timeOffset: 'UTC+12',
    time: '10:45',
    period: 'day',
    isTomorrow: true,
  },
  {
    id: 'chatham-islands',
    customName: '',
    city: 'Chatham Islands',
    timezone: 'Pacific/Chatham',
    utcOffset: 'UTC+12:45',
    timeOffset: 'UTC+12:45',
    time: '11:30',
    period: 'day',
    visible: false,
    isTomorrow: true,
  },
  {
    id: 'apia',
    customName: '',
    city: 'Apia',
    timezone: 'Pacific/Apia',
    utcOffset: 'UTC+13:00',
    timeOffset: 'UTC+13',
    time: '11:45',
    period: 'day',
    isTomorrow: true,
  },
  {
    id: 'kiritimati',
    customName: '',
    city: 'Kiritimati',
    timezone: 'Pacific/Kiritimati',
    utcOffset: 'UTC+14:00',
    timeOffset: 'UTC+14',
    time: '12:45',
    period: 'day',
    isTomorrow: true,
  },
];

const recommendedOrder: Record<string, number> = {
  'new-york': 101,
  london: 102,
  paris: 103,
  dubai: 104,
  singapore: 105,
  tokyo: 106,
  sydney: 107,
  'los-angeles': 108,
  honolulu: 109,
  'rio-de-janeiro': 110,
  'cape-town': 111,
  auckland: 112,

  'mexico-city': 201,
  santiago: 202,
  'st-johns': 203,
  'ponta-delgada': 204,
  nairobi: 205,
  tehran: 206,
  maldives: 207,
  mumbai: 208,
  kathmandu: 209,
  bangkok: 210,
  darwin: 211,
  apia: 212,
};

export const favoriteCities: FavoriteCity[] = cityFixtures
  .filter((city) => city.visible !== false)
  .map((city, index) => ({
    ...city,
    order: recommendedOrder[city.id] ?? 300 + index,
  }))
  .sort((cityA, cityB) => cityA.order - cityB.order);

export const allFavoriteCities: FavoriteCity[] = cityFixtures
  .map((city, index) => ({
    ...city,
    visible: true,
    order: recommendedOrder[city.id] ?? 300 + index,
  }))
  .sort((cityA, cityB) => cityA.order - cityB.order);

export function getOrderedFavoriteCities(cityOrder: string[]) {
  if (cityOrder.length === 0) {
    return favoriteCities;
  }

  const cityById = new Map(favoriteCities.map((city) => [city.id, city]));
  const orderedCities = cityOrder
    .map((cityId) => cityById.get(cityId))
    .filter((city): city is FavoriteCity => Boolean(city));
  const orderedCityIds = new Set(orderedCities.map((city) => city.id));
  const newCities = favoriteCities.filter((city) => !orderedCityIds.has(city.id));

  return [...orderedCities, ...newCities];
}
